import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { SharedPlannerInput } from "./route-planner.js";

// Resolved the same way the wasm-bindgen `--target web` bindings resolve it
// (relative to the generated JS module), not hand-picked for this test.
const GENERATED_WASM_PATH = fileURLToPath(
  new URL("../../../inderun-route-core-wasm/generated/inderun_route_core_bg.wasm", import.meta.url)
);

/**
 * Exercises the *browser* load path of `@independo/inderun-route-core-wasm`:
 * both dynamic imports resolve, and the module instantiates from a fetched
 * response rather than from bytes handed to it. Node cannot `fetch()` a
 * `file://` URL, so `global.fetch` is stubbed to serve the real generated bytes
 * from disk — the same bytes wasm-bindgen's
 * `new URL('inderun_route_core_bg.wasm', import.meta.url)` would fetch over the
 * network in a browser. This is the regression test for #109; every other suite
 * gets the core pre-initialized from bytes by `src/test/setup-shared-core.ts`.
 *
 * Deliberately not guarded on the bindings existing: `pnpm test:js` builds them
 * (see scripts/build-route-core-wasm.mjs), and a skip here would mean the only
 * coverage of the browser path silently disappears.
 */
describe("WasmRoutePlanner (real WASM module)", () => {
  afterEach(() => {
    vi.resetModules();
    vi.restoreAllMocks();
  });

  it("resolves both dynamic imports and produces a real plan from the WASM core", async () => {
    // Drops the module instance `setup-shared-core.ts` already initialized from
    // bytes, so the wrapper re-instantiates through its default fetch path —
    // otherwise this test would pass without the stub ever being consulted.
    vi.resetModules();

    const wasmBytes = await readFile(GENERATED_WASM_PATH);
    const realFetch = globalThis.fetch;
    const fetchSpy = vi.fn(async (input: RequestInfo | URL) => {
      const url = input instanceof URL ? input.href : input.toString();
      if (url.endsWith("inderun_route_core_bg.wasm")) {
        return new Response(wasmBytes, { headers: { "Content-Type": "application/wasm" } });
      }
      return realFetch(input);
    });
    vi.stubGlobal("fetch", fetchSpy);

    const { WasmRoutePlanner } = await import("./route-planner.js");
    const planner = new WasmRoutePlanner();

    const input: SharedPlannerInput = {
      task: { kind: "text_to_text" },
      constraints: { privacy: "cloud_allowed", cloud: "allowed", networkOnline: true },
      preferences: { optimizeFor: "balanced" },
      providers: [
        {
          descriptor: {
            id: "provider_b",
            type: "local",
            supports: { run: true },
            tasks: ["text_to_text"]
          },
          capabilities: { available: true }
        },
        {
          descriptor: {
            id: "provider_a",
            type: "local",
            supports: { run: true },
            tasks: ["text_to_text"]
          },
          capabilities: { available: true }
        }
      ]
    };

    const outcome = await planner.planRoute(input);

    expect(
      fetchSpy.mock.calls.some(([input]) =>
        (input instanceof URL ? input.href : String(input)).endsWith("inderun_route_core_bg.wasm")
      )
    ).toBe(true);
    expect(outcome.routePlan?.selectedProviderId).toBe("provider_a");
    expect(outcome.routePlan?.fallbackProviderIds).toEqual(["provider_b"]);
  });
});
