import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { afterEach, beforeAll, describe, expect, it, vi } from "vitest";
import type { SharedPlannerInput } from "./route-planner.js";

// Resolved the same way the wasm-bindgen `--target web` bindings resolve it
// (relative to the generated JS module), not hand-picked for this test.
const GENERATED_WASM_PATH = fileURLToPath(
  new URL("../../inderun-route-core-wasm/generated/inderun_route_core_bg.wasm", import.meta.url)
);

/**
 * Exercises the real (unmocked) `@independo/inderun-route-core-wasm` package:
 * both dynamic imports resolve, and the WASM module actually instantiates and
 * runs. Node cannot `fetch()` a `file://` URL, so `global.fetch` is stubbed to
 * serve the real generated bytes from disk — the same bytes wasm-bindgen's
 * `new URL('inderun_route_core_bg.wasm', import.meta.url)` would otherwise
 * fetch over the network in a browser. This is the closest in-repo proxy for
 * "does the shared Rust planner actually run" without a real browser (#109).
 *
 * Skipped when the generated WASM hasn't been built locally (it's CI-built
 * and gitignored — see docs/ci.md and packages/inderun-route-core-wasm/README.md).
 */
const generatedWasmExists = existsSync(GENERATED_WASM_PATH);

describe.skipIf(!generatedWasmExists)("WasmRoutePlanner (real WASM module)", () => {
  afterEach(() => {
    vi.resetModules();
    vi.restoreAllMocks();
  });

  beforeAll(() => {
    if (!generatedWasmExists) {
      console.warn(
        `[route-planner.wasm.test] Skipping: ${GENERATED_WASM_PATH} not found. ` +
          "Build it first — see packages/inderun-route-core-wasm/README.md."
      );
    }
  });

  it("resolves both dynamic imports and produces a real plan from the WASM core", async () => {
    const wasmBytes = await readFile(GENERATED_WASM_PATH);
    const realFetch = globalThis.fetch;
    vi.stubGlobal(
      "fetch",
      vi.fn(async (input: RequestInfo | URL) => {
        const url = input instanceof URL ? input.href : input.toString();
        if (url.endsWith("inderun_route_core_bg.wasm")) {
          return new Response(wasmBytes, { headers: { "Content-Type": "application/wasm" } });
        }
        return realFetch(input);
      })
    );

    const { WasmRoutePlanner } = await import("./route-planner.js");
    const planner = new WasmRoutePlanner();

    const input: SharedPlannerInput = {
      task: { kind: "text_to_text" },
      constraints: { privacy: "cloud_allowed", cloud: "allowed", networkOnline: true },
      preferences: { optimizeFor: "balanced" },
      providers: [
        {
          descriptor: {
            id: "provider_b",
            type: "local",
            supports: { run: true },
            tasks: ["text_to_text"]
          },
          capabilities: { available: true }
        },
        {
          descriptor: {
            id: "provider_a",
            type: "local",
            supports: { run: true },
            tasks: ["text_to_text"]
          },
          capabilities: { available: true }
        }
      ]
    };

    const outcome = await planner.planRoute(input);

    expect(outcome.source).toBe("wasm");
    expect(outcome.routePlan?.selectedProviderId).toBe("provider_a");
    expect(outcome.routePlan?.fallbackProviderIds).toEqual(["provider_b"]);
  });
});
